name = "Hexed"
author = "Walksanator"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b4fd8cc658fc956beac92dd96274eeb34ec3adf439cebb9d9f0021ffa19ddd9"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.12"
